In [19]:
my_list = ([1,2,3], [4,5,6])
my_list 


([1, 2, 3], [4, 5, 6])

#
# _____________________________________________________________________________________________
#
# Numpy
Core data structure: Numpy/Nd array

In [136]:
import numpy as np

In [20]:
my_list = np.array(my_list)
my_list

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
num = range(0,11,2)
for i in num:
    print(i) 


0
2
4
6
8
10


In [24]:
#start at 0, end at 11, take 2 steps
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [62]:
np.zeros((5,3))
np.ones([5,3,2])
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [84]:
np.random.rand(5,5) #float between 0 and 1
np.random.randn(5,5) #float in normal distribution -1,1
np.random.randint(0,4,(5,2)) #from 0, to 4 (not inclusive of 4), then give dimensions

array([[1, 3],
       [2, 3],
       [2, 1],
       [2, 2],
       [1, 2]])

# Reshaping

In [87]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [91]:
arr.reshape(5,5) #doesnt change actual arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [96]:
arr.resize(5,5) #changes actual arr
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Indexing and Slicing

In [99]:
arr = np.array(([1,2,3,4], [5,6,7,8]))
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [108]:
arr[:1,:3] #: means all rows/columns

array([[1, 2, 3]])

In [117]:
cond_array = arr > 5 #returns all elements greater than 5
cond_array
arr[cond_array]
#or
arr[arr - 3!=5] #broadcasts 3, minuses 3 from every element n compares it so the 3 actually becomes a 1x10 array of 3's

array([1, 2, 3, 4, 5, 6, 7])

In [132]:
arr[arr*([0,0,0,2],[0,0,0,0])!=0]

array([4])

# 
# ______________________________________________________________
# 

# Pandas
Core datastructure: Series & DataFrames

In [ ]:
pip install pandas

In [139]:
import pandas as pd

In [143]:
df = pd.DataFrame(data = np.random.randn(5,4))
df

0         1         2         3
0  2.826144  0.587366 -0.240317 -0.455525
1  2.208026  1.777129 -0.155855  0.848356
2 -0.230311 -0.475375  1.927108 -2.096793
3 -0.242116 -0.720303  1.109457 -1.165486
4 -0.247853 -1.627393 -0.082096  0.476884

In [166]:
df = pd.DataFrame(data = np.random.randn(5,4), index = ['A', 'B', 'C','D','E'], columns = ['column1', 'column2', 'column3','column4'] )
df

column1   column2   column3   column4
A -0.002188  0.002427  1.050507 -2.058207
B -1.346984  2.315161 -2.048583 -0.245145
C  0.346159  0.157376 -0.191799 -0.011914
D -0.895702 -1.208149  0.465323 -1.531595
E -0.017013  0.773513  1.312875 -0.322958

In [170]:
type(df['column1']) #column operation
#df.D not recommended
df[['column1', 'column2']] #returns columns

column1   column2
A -0.002188  0.002427
B -1.346984  2.315161
C  0.346159  0.157376
D -0.895702 -1.208149
E -0.017013  0.773513

In [173]:
df['column5'] = [1,2,3,4,5]
df

column1   column2   column3   column4  column5
A -0.002188  0.002427  1.050507 -2.058207        1
B -1.346984  2.315161 -2.048583 -0.245145        2
C  0.346159  0.157376 -0.191799 -0.011914        3
D -0.895702 -1.208149  0.465323 -1.531595        4
E -0.017013  0.773513  1.312875 -0.322958        5

In [187]:
df.drop('column3', axis=1) #new object, doesnt drop from actual df
df

column1   column2   column3
A -0.002188  0.002427  1.050507
B -1.346984  2.315161 -2.048583
C  0.346159  0.157376 -0.191799
D -0.895702 -1.208149  0.465323
E -0.017013  0.773513  1.312875

In [195]:
df.drop('column3', axis=1, inplace = True)
df
#or
df = df.drop('column2', axis=1)
df


column1
A -0.002188
B -1.346984
C  0.346159
D -0.895702
E -0.017013

In [197]:
df = pd.DataFrame(data = np.random.randn(5,4), index = ['A', 'B', 'C','D','E'], columns = ['column1', 'column2', 'column3','column4'] )
df

column1   column2   column3   column4
A -2.284981 -0.158008  0.612613  0.091211
B -1.978895  0.591204 -1.250868  0.564523
C -1.027207  0.671376  0.821426  0.980173
D -0.349814 -0.650317 -1.218443  0.278591
E  0.643234 -0.824824 -0.911002 -0.747342

In [208]:
df.loc['A'] #selects rows
df.iloc[0]
df

column1   column2   column3   column4
A -2.284981 -0.158008  0.612613  0.091211
B -1.978895  0.591204 -1.250868  0.564523
C -1.027207  0.671376  0.821426  0.980173
D -0.349814 -0.650317 -1.218443  0.278591
E  0.643234 -0.824824 -0.911002 -0.747342

In [218]:
df.loc['A', 'column1']

-2.284981433634867

In [224]:
df.loc[['B','C'],['column2',  'column3']] #you can use iloc with indices too

column2   column3
B  0.591204 -1.250868
C  0.671376  0.821426

In [237]:
df[(df['column1']<0) &( df['column2']<0)] #conditional indexing
#logical operations in python are 'and' and 'or', in pandas its '&' and '|'

column1   column2   column3   column4
A -2.284981 -0.158008  0.612613  0.091211
D -0.349814 -0.650317 -1.218443  0.278591

In [239]:
df.reset_index() # does a copy, doesnt change actual df, use inplace = True if u want to change it

index   column1   column2   column3   column4
0     A -2.284981 -0.158008  0.612613  0.091211
1     B -1.978895  0.591204 -1.250868  0.564523
2     C -1.027207  0.671376  0.821426  0.980173
3     D -0.349814 -0.650317 -1.218443  0.278591
4     E  0.643234 -0.824824 -0.911002 -0.747342